spring:
  #数据源
  datasource:
    url: jdbc:mysql://106.15.225.159:3306/miniprogram?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = UTC
    username: root
    password: Yuyy0800
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      enabled: true #默认支持文件上传
      max-file-size: 20MB #单个文件限制
      max-request-size: 200MB #请求总文件大小限制



#mybatis配置
mybatis:
    type-aliases-package: com.example.miniprogram.entity
    mapper-locations: classpath:mapper/*.xml
      #configLocation: classpath:/mybatis-config.xml