package com.example.miniprogram.mapper;

import com.example.miniprogram.entity.Dynamic;
import com.example.miniprogram.entity.DynamicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DynamicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    long countByExample(DynamicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    int deleteByExample(DynamicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    int deleteByPrimaryKey(Long dynamicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    int insert(Dynamic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    int insertSelective(Dynamic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    List<Dynamic> selectByExampleWithRowbounds(DynamicExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    List<Dynamic> selectByExample(DynamicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    Dynamic selectByPrimaryKey(Long dynamicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    int updateByExampleSelective(@Param("record") Dynamic record, @Param("example") DynamicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    int updateByExample(@Param("record") Dynamic record, @Param("example") DynamicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    int updateByPrimaryKeySelective(Dynamic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    int updateByPrimaryKey(Dynamic record);
}