package com.example.miniprogram.mapper;

import com.example.miniprogram.entity.Works;
import com.example.miniprogram.entity.WorksExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WorksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works
     *
     * @mbg.generated Fri May 29 13:52:00 CST 2020
     */
    long countByExample(WorksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works
     *
     * @mbg.generated Fri May 29 13:52:00 CST 2020
     */
    int deleteByExample(WorksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works
     *
     * @mbg.generated Fri May 29 13:52:00 CST 2020
     */
    int deleteByPrimaryKey(Long worksId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works
     *
     * @mbg.generated Fri May 29 13:52:00 CST 2020
     */
    int insert(Works record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works
     *
     * @mbg.generated Fri May 29 13:52:00 CST 2020
     */
    int insertSelective(Works record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works
     *
     * @mbg.generated Fri May 29 13:52:00 CST 2020
     */
    List<Works> selectByExampleWithRowbounds(WorksExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works
     *
     * @mbg.generated Fri May 29 13:52:00 CST 2020
     */
    List<Works> selectByExample(WorksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works
     *
     * @mbg.generated Fri May 29 13:52:00 CST 2020
     */
    Works selectByPrimaryKey(Long worksId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works
     *
     * @mbg.generated Fri May 29 13:52:00 CST 2020
     */
    int updateByExampleSelective(@Param("record") Works record, @Param("example") WorksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works
     *
     * @mbg.generated Fri May 29 13:52:00 CST 2020
     */
    int updateByExample(@Param("record") Works record, @Param("example") WorksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works
     *
     * @mbg.generated Fri May 29 13:52:00 CST 2020
     */
    int updateByPrimaryKeySelective(Works record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works
     *
     * @mbg.generated Fri May 29 13:52:00 CST 2020
     */
    int updateByPrimaryKey(Works record);
}