spring:
  thymeleaf:
    cache: false
  datasource:
    name: dataSource
    url: jdbc:log4jdbc:ArteryBase://IP:PORT/DATABASE
    username: username
    password: password
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  application:
    name: PageNavigationSystem
#SSO
artery:
  login:
    ssoServer: http://[IP]:[PORT]/ssoserver
 #当您需要使用组织机构的数据时,需要将您的roocorpid 设置为您需要的;例如:
  root:
    corp: 0
  #2.9版本开始增加的配置
  security:
    #当前人员数据缓存方式，支持jwt和shiro两种，默认shiro
    mode: shiro
    #调用权限接口获取权限，传入的系统标识
    system: PageNavigationSystem
    #数据缓存方式为jwt时，当前人员权限的过期时间，单位为秒，默认30分钟，
    right:
      expire: 60

#uim-api
taap:
  base:
    uimApi:
      url: http://[IP]:[PORT]/uim-api
  #配置中心，3.X
  appconfig:
    appBs: dilu.config
    #env: 可选，支持环境变量，如dev/prod/test
    # 配置中心服务端2.x，推荐配置ids(分组ID)和sysId(子系统ID)，兼容配置中心服务端3.x
    #appconfig.ids=796232cb15c14745a61b84a6efe8ccbd,a01a18be81cc41148d1ebad4921306db
    #appconfig.sysId=6dded544289b414aac5584a6efe8ccbd

# 使用说明：http://gitlab.thunisoft.com/dilu/dilu-doc/blob/master/%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3/%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3V1.2.md
# 以下为示例内容，正式使用请修改或删除
dilu:
  tab-inc:
    #指定数据库类型(ArteryBase、postgresql、mysql、sybase、oracle、dm、sqlserver、kingbase8)
    database: ArteryBase
    #登记哪些表不需要做增量记录（默认都做增量记录），多张表用逗号分隔
    exclude-zljl: db_aty.t_code,db_aty.t_corp
    # 指定表的前缀（ArteryBase、postgresql请不要指定），格式为：数据库名（db_pxxt）、数据库名.所在模式名（db_pxxt.db_ywst）
    tab-pre: db_pxxt.db_ywst
    # 登记哪些表需要做实体增量记录（默认不做实体增量），不登记就不会生效，格式为：{"模式.表名":"你的业务类型"}
    include-stzl: "{'db_pxxt.t_wz':'1','db_pxxt.t_wz2':'2'}"
