package com.example.miniprogram.entity;

import java.util.Date;

public class Appointment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.appointment_id
     *
     * @mbg.generated Sat May 16 16:38:35 CST 2020
     */
    private Long appointmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.appointment_userid1
     *
     * @mbg.generated Sat May 16 16:38:35 CST 2020
     */
    private Long appointmentUserid1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.appointment_userid2
     *
     * @mbg.generated Sat May 16 16:38:35 CST 2020
     */
    private Long appointmentUserid2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.appointment_time
     *
     * @mbg.generated Sat May 16 16:38:35 CST 2020
     */
    private Date appointmentTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.appointment_agree
     *
     * @mbg.generated Sat May 16 16:38:35 CST 2020
     */
    private Integer appointmentAgree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.appointment_reason
     *
     * @mbg.generated Sat May 16 16:38:35 CST 2020
     */
    private String appointmentReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.appointment_fromId
     *
     * @mbg.generated Sat May 16 16:38:35 CST 2020
     */
    private Long appointmentFromid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.appointment_id
     *
     * @return the value of appointment.appointment_id
     *
     * @mbg.generated Sat May 16 16:38:35 CST 2020
     */
    public Long getAppointmentId() {
        return appointmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.appointment_id
     *
     * @param appointmentId the value for appointment.appointment_id
     *
     * @mbg.generated Sat May 16 16:38:35 CST 2020
     */
    public void setAppointmentId(Long appointmentId) {
        this.appointmentId = appointmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.appointment_userid1
     *
     * @return the value of appointment.appointment_userid1
     *
     * @mbg.generated Sat May 16 16:38:35 CST 2020
     */
    public Long getAppointmentUserid1() {
        return appointmentUserid1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.appointment_userid1
     *
     * @param appointmentUserid1 the value for appointment.appointment_userid1
     *
     * @mbg.generated Sat May 16 16:38:35 CST 2020
     */
    public void setAppointmentUserid1(Long appointmentUserid1) {
        this.appointmentUserid1 = appointmentUserid1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.appointment_userid2
     *
     * @return the value of appointment.appointment_userid2
     *
     * @mbg.generated Sat May 16 16:38:35 CST 2020
     */
    public Long getAppointmentUserid2() {
        return appointmentUserid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.appointment_userid2
     *
     * @param appointmentUserid2 the value for appointment.appointment_userid2
     *
     * @mbg.generated Sat May 16 16:38:35 CST 2020
     */
    public void setAppointmentUserid2(Long appointmentUserid2) {
        this.appointmentUserid2 = appointmentUserid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.appointment_time
     *
     * @return the value of appointment.appointment_time
     *
     * @mbg.generated Sat May 16 16:38:35 CST 2020
     */
    public Date getAppointmentTime() {
        return appointmentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.appointment_time
     *
     * @param appointmentTime the value for appointment.appointment_time
     *
     * @mbg.generated Sat May 16 16:38:35 CST 2020
     */
    public void setAppointmentTime(Date appointmentTime) {
        this.appointmentTime = appointmentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.appointment_agree
     *
     * @return the value of appointment.appointment_agree
     *
     * @mbg.generated Sat May 16 16:38:35 CST 2020
     */
    public Integer getAppointmentAgree() {
        return appointmentAgree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.appointment_agree
     *
     * @param appointmentAgree the value for appointment.appointment_agree
     *
     * @mbg.generated Sat May 16 16:38:35 CST 2020
     */
    public void setAppointmentAgree(Integer appointmentAgree) {
        this.appointmentAgree = appointmentAgree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.appointment_reason
     *
     * @return the value of appointment.appointment_reason
     *
     * @mbg.generated Sat May 16 16:38:35 CST 2020
     */
    public String getAppointmentReason() {
        return appointmentReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.appointment_reason
     *
     * @param appointmentReason the value for appointment.appointment_reason
     *
     * @mbg.generated Sat May 16 16:38:35 CST 2020
     */
    public void setAppointmentReason(String appointmentReason) {
        this.appointmentReason = appointmentReason == null ? null : appointmentReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.appointment_fromId
     *
     * @return the value of appointment.appointment_fromId
     *
     * @mbg.generated Sat May 16 16:38:35 CST 2020
     */
    public Long getAppointmentFromid() {
        return appointmentFromid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.appointment_fromId
     *
     * @param appointmentFromid the value for appointment.appointment_fromId
     *
     * @mbg.generated Sat May 16 16:38:35 CST 2020
     */
    public void setAppointmentFromid(Long appointmentFromid) {
        this.appointmentFromid = appointmentFromid;
    }
}