package com.example.miniprogram.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DynamicExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dynamic
     *
     * @mbg.generated Sat May 16 16:38:35 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dynamic
     *
     * @mbg.generated Sat May 16 16:38:35 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dynamic
     *
     * @mbg.generated Sat May 16 16:38:35 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic
     *
     * @mbg.generated Sat May 16 16:38:35 CST 2020
     */
    public DynamicExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic
     *
     * @mbg.generated Sat May 16 16:38:35 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic
     *
     * @mbg.generated Sat May 16 16:38:35 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic
     *
     * @mbg.generated Sat May 16 16:38:35 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic
     *
     * @mbg.generated Sat May 16 16:38:35 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic
     *
     * @mbg.generated Sat May 16 16:38:35 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic
     *
     * @mbg.generated Sat May 16 16:38:35 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic
     *
     * @mbg.generated Sat May 16 16:38:35 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic
     *
     * @mbg.generated Sat May 16 16:38:35 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic
     *
     * @mbg.generated Sat May 16 16:38:35 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic
     *
     * @mbg.generated Sat May 16 16:38:35 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dynamic
     *
     * @mbg.generated Sat May 16 16:38:35 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDynamicIdIsNull() {
            addCriterion("dynamic_id is null");
            return (Criteria) this;
        }

        public Criteria andDynamicIdIsNotNull() {
            addCriterion("dynamic_id is not null");
            return (Criteria) this;
        }

        public Criteria andDynamicIdEqualTo(Long value) {
            addCriterion("dynamic_id =", value, "dynamicId");
            return (Criteria) this;
        }

        public Criteria andDynamicIdNotEqualTo(Long value) {
            addCriterion("dynamic_id <>", value, "dynamicId");
            return (Criteria) this;
        }

        public Criteria andDynamicIdGreaterThan(Long value) {
            addCriterion("dynamic_id >", value, "dynamicId");
            return (Criteria) this;
        }

        public Criteria andDynamicIdGreaterThanOrEqualTo(Long value) {
            addCriterion("dynamic_id >=", value, "dynamicId");
            return (Criteria) this;
        }

        public Criteria andDynamicIdLessThan(Long value) {
            addCriterion("dynamic_id <", value, "dynamicId");
            return (Criteria) this;
        }

        public Criteria andDynamicIdLessThanOrEqualTo(Long value) {
            addCriterion("dynamic_id <=", value, "dynamicId");
            return (Criteria) this;
        }

        public Criteria andDynamicIdIn(List<Long> values) {
            addCriterion("dynamic_id in", values, "dynamicId");
            return (Criteria) this;
        }

        public Criteria andDynamicIdNotIn(List<Long> values) {
            addCriterion("dynamic_id not in", values, "dynamicId");
            return (Criteria) this;
        }

        public Criteria andDynamicIdBetween(Long value1, Long value2) {
            addCriterion("dynamic_id between", value1, value2, "dynamicId");
            return (Criteria) this;
        }

        public Criteria andDynamicIdNotBetween(Long value1, Long value2) {
            addCriterion("dynamic_id not between", value1, value2, "dynamicId");
            return (Criteria) this;
        }

        public Criteria andDynamicAddressIsNull() {
            addCriterion("dynamic_address is null");
            return (Criteria) this;
        }

        public Criteria andDynamicAddressIsNotNull() {
            addCriterion("dynamic_address is not null");
            return (Criteria) this;
        }

        public Criteria andDynamicAddressEqualTo(String value) {
            addCriterion("dynamic_address =", value, "dynamicAddress");
            return (Criteria) this;
        }

        public Criteria andDynamicAddressNotEqualTo(String value) {
            addCriterion("dynamic_address <>", value, "dynamicAddress");
            return (Criteria) this;
        }

        public Criteria andDynamicAddressGreaterThan(String value) {
            addCriterion("dynamic_address >", value, "dynamicAddress");
            return (Criteria) this;
        }

        public Criteria andDynamicAddressGreaterThanOrEqualTo(String value) {
            addCriterion("dynamic_address >=", value, "dynamicAddress");
            return (Criteria) this;
        }

        public Criteria andDynamicAddressLessThan(String value) {
            addCriterion("dynamic_address <", value, "dynamicAddress");
            return (Criteria) this;
        }

        public Criteria andDynamicAddressLessThanOrEqualTo(String value) {
            addCriterion("dynamic_address <=", value, "dynamicAddress");
            return (Criteria) this;
        }

        public Criteria andDynamicAddressLike(String value) {
            addCriterion("dynamic_address like", value, "dynamicAddress");
            return (Criteria) this;
        }

        public Criteria andDynamicAddressNotLike(String value) {
            addCriterion("dynamic_address not like", value, "dynamicAddress");
            return (Criteria) this;
        }

        public Criteria andDynamicAddressIn(List<String> values) {
            addCriterion("dynamic_address in", values, "dynamicAddress");
            return (Criteria) this;
        }

        public Criteria andDynamicAddressNotIn(List<String> values) {
            addCriterion("dynamic_address not in", values, "dynamicAddress");
            return (Criteria) this;
        }

        public Criteria andDynamicAddressBetween(String value1, String value2) {
            addCriterion("dynamic_address between", value1, value2, "dynamicAddress");
            return (Criteria) this;
        }

        public Criteria andDynamicAddressNotBetween(String value1, String value2) {
            addCriterion("dynamic_address not between", value1, value2, "dynamicAddress");
            return (Criteria) this;
        }

        public Criteria andDynamicRequireIsNull() {
            addCriterion("dynamic_require is null");
            return (Criteria) this;
        }

        public Criteria andDynamicRequireIsNotNull() {
            addCriterion("dynamic_require is not null");
            return (Criteria) this;
        }

        public Criteria andDynamicRequireEqualTo(String value) {
            addCriterion("dynamic_require =", value, "dynamicRequire");
            return (Criteria) this;
        }

        public Criteria andDynamicRequireNotEqualTo(String value) {
            addCriterion("dynamic_require <>", value, "dynamicRequire");
            return (Criteria) this;
        }

        public Criteria andDynamicRequireGreaterThan(String value) {
            addCriterion("dynamic_require >", value, "dynamicRequire");
            return (Criteria) this;
        }

        public Criteria andDynamicRequireGreaterThanOrEqualTo(String value) {
            addCriterion("dynamic_require >=", value, "dynamicRequire");
            return (Criteria) this;
        }

        public Criteria andDynamicRequireLessThan(String value) {
            addCriterion("dynamic_require <", value, "dynamicRequire");
            return (Criteria) this;
        }

        public Criteria andDynamicRequireLessThanOrEqualTo(String value) {
            addCriterion("dynamic_require <=", value, "dynamicRequire");
            return (Criteria) this;
        }

        public Criteria andDynamicRequireLike(String value) {
            addCriterion("dynamic_require like", value, "dynamicRequire");
            return (Criteria) this;
        }

        public Criteria andDynamicRequireNotLike(String value) {
            addCriterion("dynamic_require not like", value, "dynamicRequire");
            return (Criteria) this;
        }

        public Criteria andDynamicRequireIn(List<String> values) {
            addCriterion("dynamic_require in", values, "dynamicRequire");
            return (Criteria) this;
        }

        public Criteria andDynamicRequireNotIn(List<String> values) {
            addCriterion("dynamic_require not in", values, "dynamicRequire");
            return (Criteria) this;
        }

        public Criteria andDynamicRequireBetween(String value1, String value2) {
            addCriterion("dynamic_require between", value1, value2, "dynamicRequire");
            return (Criteria) this;
        }

        public Criteria andDynamicRequireNotBetween(String value1, String value2) {
            addCriterion("dynamic_require not between", value1, value2, "dynamicRequire");
            return (Criteria) this;
        }

        public Criteria andDynamicDateIsNull() {
            addCriterion("dynamic_date is null");
            return (Criteria) this;
        }

        public Criteria andDynamicDateIsNotNull() {
            addCriterion("dynamic_date is not null");
            return (Criteria) this;
        }

        public Criteria andDynamicDateEqualTo(String value) {
            addCriterion("dynamic_date =", value, "dynamicDate");
            return (Criteria) this;
        }

        public Criteria andDynamicDateNotEqualTo(String value) {
            addCriterion("dynamic_date <>", value, "dynamicDate");
            return (Criteria) this;
        }

        public Criteria andDynamicDateGreaterThan(String value) {
            addCriterion("dynamic_date >", value, "dynamicDate");
            return (Criteria) this;
        }

        public Criteria andDynamicDateGreaterThanOrEqualTo(String value) {
            addCriterion("dynamic_date >=", value, "dynamicDate");
            return (Criteria) this;
        }

        public Criteria andDynamicDateLessThan(String value) {
            addCriterion("dynamic_date <", value, "dynamicDate");
            return (Criteria) this;
        }

        public Criteria andDynamicDateLessThanOrEqualTo(String value) {
            addCriterion("dynamic_date <=", value, "dynamicDate");
            return (Criteria) this;
        }

        public Criteria andDynamicDateLike(String value) {
            addCriterion("dynamic_date like", value, "dynamicDate");
            return (Criteria) this;
        }

        public Criteria andDynamicDateNotLike(String value) {
            addCriterion("dynamic_date not like", value, "dynamicDate");
            return (Criteria) this;
        }

        public Criteria andDynamicDateIn(List<String> values) {
            addCriterion("dynamic_date in", values, "dynamicDate");
            return (Criteria) this;
        }

        public Criteria andDynamicDateNotIn(List<String> values) {
            addCriterion("dynamic_date not in", values, "dynamicDate");
            return (Criteria) this;
        }

        public Criteria andDynamicDateBetween(String value1, String value2) {
            addCriterion("dynamic_date between", value1, value2, "dynamicDate");
            return (Criteria) this;
        }

        public Criteria andDynamicDateNotBetween(String value1, String value2) {
            addCriterion("dynamic_date not between", value1, value2, "dynamicDate");
            return (Criteria) this;
        }

        public Criteria andDynamicAreaIsNull() {
            addCriterion("dynamic_area is null");
            return (Criteria) this;
        }

        public Criteria andDynamicAreaIsNotNull() {
            addCriterion("dynamic_area is not null");
            return (Criteria) this;
        }

        public Criteria andDynamicAreaEqualTo(String value) {
            addCriterion("dynamic_area =", value, "dynamicArea");
            return (Criteria) this;
        }

        public Criteria andDynamicAreaNotEqualTo(String value) {
            addCriterion("dynamic_area <>", value, "dynamicArea");
            return (Criteria) this;
        }

        public Criteria andDynamicAreaGreaterThan(String value) {
            addCriterion("dynamic_area >", value, "dynamicArea");
            return (Criteria) this;
        }

        public Criteria andDynamicAreaGreaterThanOrEqualTo(String value) {
            addCriterion("dynamic_area >=", value, "dynamicArea");
            return (Criteria) this;
        }

        public Criteria andDynamicAreaLessThan(String value) {
            addCriterion("dynamic_area <", value, "dynamicArea");
            return (Criteria) this;
        }

        public Criteria andDynamicAreaLessThanOrEqualTo(String value) {
            addCriterion("dynamic_area <=", value, "dynamicArea");
            return (Criteria) this;
        }

        public Criteria andDynamicAreaLike(String value) {
            addCriterion("dynamic_area like", value, "dynamicArea");
            return (Criteria) this;
        }

        public Criteria andDynamicAreaNotLike(String value) {
            addCriterion("dynamic_area not like", value, "dynamicArea");
            return (Criteria) this;
        }

        public Criteria andDynamicAreaIn(List<String> values) {
            addCriterion("dynamic_area in", values, "dynamicArea");
            return (Criteria) this;
        }

        public Criteria andDynamicAreaNotIn(List<String> values) {
            addCriterion("dynamic_area not in", values, "dynamicArea");
            return (Criteria) this;
        }

        public Criteria andDynamicAreaBetween(String value1, String value2) {
            addCriterion("dynamic_area between", value1, value2, "dynamicArea");
            return (Criteria) this;
        }

        public Criteria andDynamicAreaNotBetween(String value1, String value2) {
            addCriterion("dynamic_area not between", value1, value2, "dynamicArea");
            return (Criteria) this;
        }

        public Criteria andDynamicWhoIsNull() {
            addCriterion("dynamic_who is null");
            return (Criteria) this;
        }

        public Criteria andDynamicWhoIsNotNull() {
            addCriterion("dynamic_who is not null");
            return (Criteria) this;
        }

        public Criteria andDynamicWhoEqualTo(String value) {
            addCriterion("dynamic_who =", value, "dynamicWho");
            return (Criteria) this;
        }

        public Criteria andDynamicWhoNotEqualTo(String value) {
            addCriterion("dynamic_who <>", value, "dynamicWho");
            return (Criteria) this;
        }

        public Criteria andDynamicWhoGreaterThan(String value) {
            addCriterion("dynamic_who >", value, "dynamicWho");
            return (Criteria) this;
        }

        public Criteria andDynamicWhoGreaterThanOrEqualTo(String value) {
            addCriterion("dynamic_who >=", value, "dynamicWho");
            return (Criteria) this;
        }

        public Criteria andDynamicWhoLessThan(String value) {
            addCriterion("dynamic_who <", value, "dynamicWho");
            return (Criteria) this;
        }

        public Criteria andDynamicWhoLessThanOrEqualTo(String value) {
            addCriterion("dynamic_who <=", value, "dynamicWho");
            return (Criteria) this;
        }

        public Criteria andDynamicWhoLike(String value) {
            addCriterion("dynamic_who like", value, "dynamicWho");
            return (Criteria) this;
        }

        public Criteria andDynamicWhoNotLike(String value) {
            addCriterion("dynamic_who not like", value, "dynamicWho");
            return (Criteria) this;
        }

        public Criteria andDynamicWhoIn(List<String> values) {
            addCriterion("dynamic_who in", values, "dynamicWho");
            return (Criteria) this;
        }

        public Criteria andDynamicWhoNotIn(List<String> values) {
            addCriterion("dynamic_who not in", values, "dynamicWho");
            return (Criteria) this;
        }

        public Criteria andDynamicWhoBetween(String value1, String value2) {
            addCriterion("dynamic_who between", value1, value2, "dynamicWho");
            return (Criteria) this;
        }

        public Criteria andDynamicWhoNotBetween(String value1, String value2) {
            addCriterion("dynamic_who not between", value1, value2, "dynamicWho");
            return (Criteria) this;
        }

        public Criteria andDynamicNumIsNull() {
            addCriterion("dynamic_num is null");
            return (Criteria) this;
        }

        public Criteria andDynamicNumIsNotNull() {
            addCriterion("dynamic_num is not null");
            return (Criteria) this;
        }

        public Criteria andDynamicNumEqualTo(Long value) {
            addCriterion("dynamic_num =", value, "dynamicNum");
            return (Criteria) this;
        }

        public Criteria andDynamicNumNotEqualTo(Long value) {
            addCriterion("dynamic_num <>", value, "dynamicNum");
            return (Criteria) this;
        }

        public Criteria andDynamicNumGreaterThan(Long value) {
            addCriterion("dynamic_num >", value, "dynamicNum");
            return (Criteria) this;
        }

        public Criteria andDynamicNumGreaterThanOrEqualTo(Long value) {
            addCriterion("dynamic_num >=", value, "dynamicNum");
            return (Criteria) this;
        }

        public Criteria andDynamicNumLessThan(Long value) {
            addCriterion("dynamic_num <", value, "dynamicNum");
            return (Criteria) this;
        }

        public Criteria andDynamicNumLessThanOrEqualTo(Long value) {
            addCriterion("dynamic_num <=", value, "dynamicNum");
            return (Criteria) this;
        }

        public Criteria andDynamicNumIn(List<Long> values) {
            addCriterion("dynamic_num in", values, "dynamicNum");
            return (Criteria) this;
        }

        public Criteria andDynamicNumNotIn(List<Long> values) {
            addCriterion("dynamic_num not in", values, "dynamicNum");
            return (Criteria) this;
        }

        public Criteria andDynamicNumBetween(Long value1, Long value2) {
            addCriterion("dynamic_num between", value1, value2, "dynamicNum");
            return (Criteria) this;
        }

        public Criteria andDynamicNumNotBetween(Long value1, Long value2) {
            addCriterion("dynamic_num not between", value1, value2, "dynamicNum");
            return (Criteria) this;
        }

        public Criteria andDynamicTimeIsNull() {
            addCriterion("dynamic_time is null");
            return (Criteria) this;
        }

        public Criteria andDynamicTimeIsNotNull() {
            addCriterion("dynamic_time is not null");
            return (Criteria) this;
        }

        public Criteria andDynamicTimeEqualTo(Date value) {
            addCriterion("dynamic_time =", value, "dynamicTime");
            return (Criteria) this;
        }

        public Criteria andDynamicTimeNotEqualTo(Date value) {
            addCriterion("dynamic_time <>", value, "dynamicTime");
            return (Criteria) this;
        }

        public Criteria andDynamicTimeGreaterThan(Date value) {
            addCriterion("dynamic_time >", value, "dynamicTime");
            return (Criteria) this;
        }

        public Criteria andDynamicTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("dynamic_time >=", value, "dynamicTime");
            return (Criteria) this;
        }

        public Criteria andDynamicTimeLessThan(Date value) {
            addCriterion("dynamic_time <", value, "dynamicTime");
            return (Criteria) this;
        }

        public Criteria andDynamicTimeLessThanOrEqualTo(Date value) {
            addCriterion("dynamic_time <=", value, "dynamicTime");
            return (Criteria) this;
        }

        public Criteria andDynamicTimeIn(List<Date> values) {
            addCriterion("dynamic_time in", values, "dynamicTime");
            return (Criteria) this;
        }

        public Criteria andDynamicTimeNotIn(List<Date> values) {
            addCriterion("dynamic_time not in", values, "dynamicTime");
            return (Criteria) this;
        }

        public Criteria andDynamicTimeBetween(Date value1, Date value2) {
            addCriterion("dynamic_time between", value1, value2, "dynamicTime");
            return (Criteria) this;
        }

        public Criteria andDynamicTimeNotBetween(Date value1, Date value2) {
            addCriterion("dynamic_time not between", value1, value2, "dynamicTime");
            return (Criteria) this;
        }

        public Criteria andDynamicMoneyIsNull() {
            addCriterion("dynamic_money is null");
            return (Criteria) this;
        }

        public Criteria andDynamicMoneyIsNotNull() {
            addCriterion("dynamic_money is not null");
            return (Criteria) this;
        }

        public Criteria andDynamicMoneyEqualTo(String value) {
            addCriterion("dynamic_money =", value, "dynamicMoney");
            return (Criteria) this;
        }

        public Criteria andDynamicMoneyNotEqualTo(String value) {
            addCriterion("dynamic_money <>", value, "dynamicMoney");
            return (Criteria) this;
        }

        public Criteria andDynamicMoneyGreaterThan(String value) {
            addCriterion("dynamic_money >", value, "dynamicMoney");
            return (Criteria) this;
        }

        public Criteria andDynamicMoneyGreaterThanOrEqualTo(String value) {
            addCriterion("dynamic_money >=", value, "dynamicMoney");
            return (Criteria) this;
        }

        public Criteria andDynamicMoneyLessThan(String value) {
            addCriterion("dynamic_money <", value, "dynamicMoney");
            return (Criteria) this;
        }

        public Criteria andDynamicMoneyLessThanOrEqualTo(String value) {
            addCriterion("dynamic_money <=", value, "dynamicMoney");
            return (Criteria) this;
        }

        public Criteria andDynamicMoneyLike(String value) {
            addCriterion("dynamic_money like", value, "dynamicMoney");
            return (Criteria) this;
        }

        public Criteria andDynamicMoneyNotLike(String value) {
            addCriterion("dynamic_money not like", value, "dynamicMoney");
            return (Criteria) this;
        }

        public Criteria andDynamicMoneyIn(List<String> values) {
            addCriterion("dynamic_money in", values, "dynamicMoney");
            return (Criteria) this;
        }

        public Criteria andDynamicMoneyNotIn(List<String> values) {
            addCriterion("dynamic_money not in", values, "dynamicMoney");
            return (Criteria) this;
        }

        public Criteria andDynamicMoneyBetween(String value1, String value2) {
            addCriterion("dynamic_money between", value1, value2, "dynamicMoney");
            return (Criteria) this;
        }

        public Criteria andDynamicMoneyNotBetween(String value1, String value2) {
            addCriterion("dynamic_money not between", value1, value2, "dynamicMoney");
            return (Criteria) this;
        }

        public Criteria andDynamicFinishIsNull() {
            addCriterion("dynamic_finish is null");
            return (Criteria) this;
        }

        public Criteria andDynamicFinishIsNotNull() {
            addCriterion("dynamic_finish is not null");
            return (Criteria) this;
        }

        public Criteria andDynamicFinishEqualTo(String value) {
            addCriterion("dynamic_finish =", value, "dynamicFinish");
            return (Criteria) this;
        }

        public Criteria andDynamicFinishNotEqualTo(String value) {
            addCriterion("dynamic_finish <>", value, "dynamicFinish");
            return (Criteria) this;
        }

        public Criteria andDynamicFinishGreaterThan(String value) {
            addCriterion("dynamic_finish >", value, "dynamicFinish");
            return (Criteria) this;
        }

        public Criteria andDynamicFinishGreaterThanOrEqualTo(String value) {
            addCriterion("dynamic_finish >=", value, "dynamicFinish");
            return (Criteria) this;
        }

        public Criteria andDynamicFinishLessThan(String value) {
            addCriterion("dynamic_finish <", value, "dynamicFinish");
            return (Criteria) this;
        }

        public Criteria andDynamicFinishLessThanOrEqualTo(String value) {
            addCriterion("dynamic_finish <=", value, "dynamicFinish");
            return (Criteria) this;
        }

        public Criteria andDynamicFinishLike(String value) {
            addCriterion("dynamic_finish like", value, "dynamicFinish");
            return (Criteria) this;
        }

        public Criteria andDynamicFinishNotLike(String value) {
            addCriterion("dynamic_finish not like", value, "dynamicFinish");
            return (Criteria) this;
        }

        public Criteria andDynamicFinishIn(List<String> values) {
            addCriterion("dynamic_finish in", values, "dynamicFinish");
            return (Criteria) this;
        }

        public Criteria andDynamicFinishNotIn(List<String> values) {
            addCriterion("dynamic_finish not in", values, "dynamicFinish");
            return (Criteria) this;
        }

        public Criteria andDynamicFinishBetween(String value1, String value2) {
            addCriterion("dynamic_finish between", value1, value2, "dynamicFinish");
            return (Criteria) this;
        }

        public Criteria andDynamicFinishNotBetween(String value1, String value2) {
            addCriterion("dynamic_finish not between", value1, value2, "dynamicFinish");
            return (Criteria) this;
        }

        public Criteria andDynamicImgIsNull() {
            addCriterion("dynamic_img is null");
            return (Criteria) this;
        }

        public Criteria andDynamicImgIsNotNull() {
            addCriterion("dynamic_img is not null");
            return (Criteria) this;
        }

        public Criteria andDynamicImgEqualTo(String value) {
            addCriterion("dynamic_img =", value, "dynamicImg");
            return (Criteria) this;
        }

        public Criteria andDynamicImgNotEqualTo(String value) {
            addCriterion("dynamic_img <>", value, "dynamicImg");
            return (Criteria) this;
        }

        public Criteria andDynamicImgGreaterThan(String value) {
            addCriterion("dynamic_img >", value, "dynamicImg");
            return (Criteria) this;
        }

        public Criteria andDynamicImgGreaterThanOrEqualTo(String value) {
            addCriterion("dynamic_img >=", value, "dynamicImg");
            return (Criteria) this;
        }

        public Criteria andDynamicImgLessThan(String value) {
            addCriterion("dynamic_img <", value, "dynamicImg");
            return (Criteria) this;
        }

        public Criteria andDynamicImgLessThanOrEqualTo(String value) {
            addCriterion("dynamic_img <=", value, "dynamicImg");
            return (Criteria) this;
        }

        public Criteria andDynamicImgLike(String value) {
            addCriterion("dynamic_img like", value, "dynamicImg");
            return (Criteria) this;
        }

        public Criteria andDynamicImgNotLike(String value) {
            addCriterion("dynamic_img not like", value, "dynamicImg");
            return (Criteria) this;
        }

        public Criteria andDynamicImgIn(List<String> values) {
            addCriterion("dynamic_img in", values, "dynamicImg");
            return (Criteria) this;
        }

        public Criteria andDynamicImgNotIn(List<String> values) {
            addCriterion("dynamic_img not in", values, "dynamicImg");
            return (Criteria) this;
        }

        public Criteria andDynamicImgBetween(String value1, String value2) {
            addCriterion("dynamic_img between", value1, value2, "dynamicImg");
            return (Criteria) this;
        }

        public Criteria andDynamicImgNotBetween(String value1, String value2) {
            addCriterion("dynamic_img not between", value1, value2, "dynamicImg");
            return (Criteria) this;
        }

        public Criteria andDynamicStyleIsNull() {
            addCriterion("dynamic_style is null");
            return (Criteria) this;
        }

        public Criteria andDynamicStyleIsNotNull() {
            addCriterion("dynamic_style is not null");
            return (Criteria) this;
        }

        public Criteria andDynamicStyleEqualTo(String value) {
            addCriterion("dynamic_style =", value, "dynamicStyle");
            return (Criteria) this;
        }

        public Criteria andDynamicStyleNotEqualTo(String value) {
            addCriterion("dynamic_style <>", value, "dynamicStyle");
            return (Criteria) this;
        }

        public Criteria andDynamicStyleGreaterThan(String value) {
            addCriterion("dynamic_style >", value, "dynamicStyle");
            return (Criteria) this;
        }

        public Criteria andDynamicStyleGreaterThanOrEqualTo(String value) {
            addCriterion("dynamic_style >=", value, "dynamicStyle");
            return (Criteria) this;
        }

        public Criteria andDynamicStyleLessThan(String value) {
            addCriterion("dynamic_style <", value, "dynamicStyle");
            return (Criteria) this;
        }

        public Criteria andDynamicStyleLessThanOrEqualTo(String value) {
            addCriterion("dynamic_style <=", value, "dynamicStyle");
            return (Criteria) this;
        }

        public Criteria andDynamicStyleLike(String value) {
            addCriterion("dynamic_style like", value, "dynamicStyle");
            return (Criteria) this;
        }

        public Criteria andDynamicStyleNotLike(String value) {
            addCriterion("dynamic_style not like", value, "dynamicStyle");
            return (Criteria) this;
        }

        public Criteria andDynamicStyleIn(List<String> values) {
            addCriterion("dynamic_style in", values, "dynamicStyle");
            return (Criteria) this;
        }

        public Criteria andDynamicStyleNotIn(List<String> values) {
            addCriterion("dynamic_style not in", values, "dynamicStyle");
            return (Criteria) this;
        }

        public Criteria andDynamicStyleBetween(String value1, String value2) {
            addCriterion("dynamic_style between", value1, value2, "dynamicStyle");
            return (Criteria) this;
        }

        public Criteria andDynamicStyleNotBetween(String value1, String value2) {
            addCriterion("dynamic_style not between", value1, value2, "dynamicStyle");
            return (Criteria) this;
        }

        public Criteria andDynamicUseridIsNull() {
            addCriterion("dynamic_userid is null");
            return (Criteria) this;
        }

        public Criteria andDynamicUseridIsNotNull() {
            addCriterion("dynamic_userid is not null");
            return (Criteria) this;
        }

        public Criteria andDynamicUseridEqualTo(Long value) {
            addCriterion("dynamic_userid =", value, "dynamicUserid");
            return (Criteria) this;
        }

        public Criteria andDynamicUseridNotEqualTo(Long value) {
            addCriterion("dynamic_userid <>", value, "dynamicUserid");
            return (Criteria) this;
        }

        public Criteria andDynamicUseridGreaterThan(Long value) {
            addCriterion("dynamic_userid >", value, "dynamicUserid");
            return (Criteria) this;
        }

        public Criteria andDynamicUseridGreaterThanOrEqualTo(Long value) {
            addCriterion("dynamic_userid >=", value, "dynamicUserid");
            return (Criteria) this;
        }

        public Criteria andDynamicUseridLessThan(Long value) {
            addCriterion("dynamic_userid <", value, "dynamicUserid");
            return (Criteria) this;
        }

        public Criteria andDynamicUseridLessThanOrEqualTo(Long value) {
            addCriterion("dynamic_userid <=", value, "dynamicUserid");
            return (Criteria) this;
        }

        public Criteria andDynamicUseridIn(List<Long> values) {
            addCriterion("dynamic_userid in", values, "dynamicUserid");
            return (Criteria) this;
        }

        public Criteria andDynamicUseridNotIn(List<Long> values) {
            addCriterion("dynamic_userid not in", values, "dynamicUserid");
            return (Criteria) this;
        }

        public Criteria andDynamicUseridBetween(Long value1, Long value2) {
            addCriterion("dynamic_userid between", value1, value2, "dynamicUserid");
            return (Criteria) this;
        }

        public Criteria andDynamicUseridNotBetween(Long value1, Long value2) {
            addCriterion("dynamic_userid not between", value1, value2, "dynamicUserid");
            return (Criteria) this;
        }

        public Criteria andDynamicGenderIsNull() {
            addCriterion("dynamic_gender is null");
            return (Criteria) this;
        }

        public Criteria andDynamicGenderIsNotNull() {
            addCriterion("dynamic_gender is not null");
            return (Criteria) this;
        }

        public Criteria andDynamicGenderEqualTo(String value) {
            addCriterion("dynamic_gender =", value, "dynamicGender");
            return (Criteria) this;
        }

        public Criteria andDynamicGenderNotEqualTo(String value) {
            addCriterion("dynamic_gender <>", value, "dynamicGender");
            return (Criteria) this;
        }

        public Criteria andDynamicGenderGreaterThan(String value) {
            addCriterion("dynamic_gender >", value, "dynamicGender");
            return (Criteria) this;
        }

        public Criteria andDynamicGenderGreaterThanOrEqualTo(String value) {
            addCriterion("dynamic_gender >=", value, "dynamicGender");
            return (Criteria) this;
        }

        public Criteria andDynamicGenderLessThan(String value) {
            addCriterion("dynamic_gender <", value, "dynamicGender");
            return (Criteria) this;
        }

        public Criteria andDynamicGenderLessThanOrEqualTo(String value) {
            addCriterion("dynamic_gender <=", value, "dynamicGender");
            return (Criteria) this;
        }

        public Criteria andDynamicGenderLike(String value) {
            addCriterion("dynamic_gender like", value, "dynamicGender");
            return (Criteria) this;
        }

        public Criteria andDynamicGenderNotLike(String value) {
            addCriterion("dynamic_gender not like", value, "dynamicGender");
            return (Criteria) this;
        }

        public Criteria andDynamicGenderIn(List<String> values) {
            addCriterion("dynamic_gender in", values, "dynamicGender");
            return (Criteria) this;
        }

        public Criteria andDynamicGenderNotIn(List<String> values) {
            addCriterion("dynamic_gender not in", values, "dynamicGender");
            return (Criteria) this;
        }

        public Criteria andDynamicGenderBetween(String value1, String value2) {
            addCriterion("dynamic_gender between", value1, value2, "dynamicGender");
            return (Criteria) this;
        }

        public Criteria andDynamicGenderNotBetween(String value1, String value2) {
            addCriterion("dynamic_gender not between", value1, value2, "dynamicGender");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dynamic
     *
     * @mbg.generated do_not_delete_during_merge Sat May 16 16:38:35 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dynamic
     *
     * @mbg.generated Sat May 16 16:38:35 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}