package com.example.miniprogram.entity;

public class Dynamic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic.dynamic_id
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    private Long dynamicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic.dynamic_address
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    private String dynamicAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic.dynamic_require
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    private String dynamicRequire;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic.dynamic_date
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    private String dynamicDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic.dynamic_area
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    private String dynamicArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic.dynamic_who
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    private String dynamicWho;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic.dynamic_num
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    private Long dynamicNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic.dynamic_time
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    private String dynamicTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic.dynamic_money
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    private String dynamicMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic.dynamic_finish
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    private String dynamicFinish;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic.dynamic_img
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    private String dynamicImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic.dynamic_style
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    private String dynamicStyle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic.dynamic_userid
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    private Long dynamicUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic.dynamic_gender
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    private String dynamicGender;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic.dynamic_id
     *
     * @return the value of dynamic.dynamic_id
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    public Long getDynamicId() {
        return dynamicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic.dynamic_id
     *
     * @param dynamicId the value for dynamic.dynamic_id
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    public void setDynamicId(Long dynamicId) {
        this.dynamicId = dynamicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic.dynamic_address
     *
     * @return the value of dynamic.dynamic_address
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    public String getDynamicAddress() {
        return dynamicAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic.dynamic_address
     *
     * @param dynamicAddress the value for dynamic.dynamic_address
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    public void setDynamicAddress(String dynamicAddress) {
        this.dynamicAddress = dynamicAddress == null ? null : dynamicAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic.dynamic_require
     *
     * @return the value of dynamic.dynamic_require
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    public String getDynamicRequire() {
        return dynamicRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic.dynamic_require
     *
     * @param dynamicRequire the value for dynamic.dynamic_require
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    public void setDynamicRequire(String dynamicRequire) {
        this.dynamicRequire = dynamicRequire == null ? null : dynamicRequire.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic.dynamic_date
     *
     * @return the value of dynamic.dynamic_date
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    public String getDynamicDate() {
        return dynamicDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic.dynamic_date
     *
     * @param dynamicDate the value for dynamic.dynamic_date
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    public void setDynamicDate(String dynamicDate) {
        this.dynamicDate = dynamicDate == null ? null : dynamicDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic.dynamic_area
     *
     * @return the value of dynamic.dynamic_area
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    public String getDynamicArea() {
        return dynamicArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic.dynamic_area
     *
     * @param dynamicArea the value for dynamic.dynamic_area
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    public void setDynamicArea(String dynamicArea) {
        this.dynamicArea = dynamicArea == null ? null : dynamicArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic.dynamic_who
     *
     * @return the value of dynamic.dynamic_who
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    public String getDynamicWho() {
        return dynamicWho;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic.dynamic_who
     *
     * @param dynamicWho the value for dynamic.dynamic_who
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    public void setDynamicWho(String dynamicWho) {
        this.dynamicWho = dynamicWho == null ? null : dynamicWho.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic.dynamic_num
     *
     * @return the value of dynamic.dynamic_num
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    public Long getDynamicNum() {
        return dynamicNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic.dynamic_num
     *
     * @param dynamicNum the value for dynamic.dynamic_num
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    public void setDynamicNum(Long dynamicNum) {
        this.dynamicNum = dynamicNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic.dynamic_time
     *
     * @return the value of dynamic.dynamic_time
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    public String getDynamicTime() {
        return dynamicTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic.dynamic_time
     *
     * @param dynamicTime the value for dynamic.dynamic_time
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    public void setDynamicTime(String dynamicTime) {
        this.dynamicTime = dynamicTime == null ? null : dynamicTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic.dynamic_money
     *
     * @return the value of dynamic.dynamic_money
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    public String getDynamicMoney() {
        return dynamicMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic.dynamic_money
     *
     * @param dynamicMoney the value for dynamic.dynamic_money
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    public void setDynamicMoney(String dynamicMoney) {
        this.dynamicMoney = dynamicMoney == null ? null : dynamicMoney.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic.dynamic_finish
     *
     * @return the value of dynamic.dynamic_finish
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    public String getDynamicFinish() {
        return dynamicFinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic.dynamic_finish
     *
     * @param dynamicFinish the value for dynamic.dynamic_finish
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    public void setDynamicFinish(String dynamicFinish) {
        this.dynamicFinish = dynamicFinish == null ? null : dynamicFinish.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic.dynamic_img
     *
     * @return the value of dynamic.dynamic_img
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    public String getDynamicImg() {
        return dynamicImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic.dynamic_img
     *
     * @param dynamicImg the value for dynamic.dynamic_img
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    public void setDynamicImg(String dynamicImg) {
        this.dynamicImg = dynamicImg == null ? null : dynamicImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic.dynamic_style
     *
     * @return the value of dynamic.dynamic_style
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    public String getDynamicStyle() {
        return dynamicStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic.dynamic_style
     *
     * @param dynamicStyle the value for dynamic.dynamic_style
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    public void setDynamicStyle(String dynamicStyle) {
        this.dynamicStyle = dynamicStyle == null ? null : dynamicStyle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic.dynamic_userid
     *
     * @return the value of dynamic.dynamic_userid
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    public Long getDynamicUserid() {
        return dynamicUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic.dynamic_userid
     *
     * @param dynamicUserid the value for dynamic.dynamic_userid
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    public void setDynamicUserid(Long dynamicUserid) {
        this.dynamicUserid = dynamicUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic.dynamic_gender
     *
     * @return the value of dynamic.dynamic_gender
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    public String getDynamicGender() {
        return dynamicGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic.dynamic_gender
     *
     * @param dynamicGender the value for dynamic.dynamic_gender
     *
     * @mbg.generated Thu May 28 16:06:05 CST 2020
     */
    public void setDynamicGender(String dynamicGender) {
        this.dynamicGender = dynamicGender == null ? null : dynamicGender.trim();
    }
}