package com.example.miniprogram.entity;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_name
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_gender
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    private String userGender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_avater
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    private String userAvater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_birthday
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    private Date userBirthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_address
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    private String userAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_identity
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    private String userIdentity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_describe
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    private String userDescribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_phone
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    private String userPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_wx
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    private String userWx;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_name
     *
     * @return the value of user.user_name
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_name
     *
     * @param userName the value for user.user_name
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_gender
     *
     * @return the value of user.user_gender
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    public String getUserGender() {
        return userGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_gender
     *
     * @param userGender the value for user.user_gender
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    public void setUserGender(String userGender) {
        this.userGender = userGender == null ? null : userGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_avater
     *
     * @return the value of user.user_avater
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    public String getUserAvater() {
        return userAvater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_avater
     *
     * @param userAvater the value for user.user_avater
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    public void setUserAvater(String userAvater) {
        this.userAvater = userAvater == null ? null : userAvater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_birthday
     *
     * @return the value of user.user_birthday
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    public Date getUserBirthday() {
        return userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_birthday
     *
     * @param userBirthday the value for user.user_birthday
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    public void setUserBirthday(Date userBirthday) {
        this.userBirthday = userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_address
     *
     * @return the value of user.user_address
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    public String getUserAddress() {
        return userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_address
     *
     * @param userAddress the value for user.user_address
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress == null ? null : userAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_identity
     *
     * @return the value of user.user_identity
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    public String getUserIdentity() {
        return userIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_identity
     *
     * @param userIdentity the value for user.user_identity
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    public void setUserIdentity(String userIdentity) {
        this.userIdentity = userIdentity == null ? null : userIdentity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_describe
     *
     * @return the value of user.user_describe
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    public String getUserDescribe() {
        return userDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_describe
     *
     * @param userDescribe the value for user.user_describe
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    public void setUserDescribe(String userDescribe) {
        this.userDescribe = userDescribe == null ? null : userDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_phone
     *
     * @return the value of user.user_phone
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_phone
     *
     * @param userPhone the value for user.user_phone
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_wx
     *
     * @return the value of user.user_wx
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    public String getUserWx() {
        return userWx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_wx
     *
     * @param userWx the value for user.user_wx
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    public void setUserWx(String userWx) {
        this.userWx = userWx == null ? null : userWx.trim();
    }
}