package com.example.miniprogram.entity;

public class Works {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.works_id
     *
     * @mbg.generated Fri May 29 13:52:00 CST 2020
     */
    private Long worksId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.works_img
     *
     * @mbg.generated Fri May 29 13:52:00 CST 2020
     */
    private String worksImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.works_describe
     *
     * @mbg.generated Fri May 29 13:52:00 CST 2020
     */
    private String worksDescribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.works_equiment
     *
     * @mbg.generated Fri May 29 13:52:00 CST 2020
     */
    private String worksEquiment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.works_time
     *
     * @mbg.generated Fri May 29 13:52:00 CST 2020
     */
    private String worksTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.works_style
     *
     * @mbg.generated Fri May 29 13:52:00 CST 2020
     */
    private String worksStyle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.works_givephoto
     *
     * @mbg.generated Fri May 29 13:52:00 CST 2020
     */
    private Integer worksGivephoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.works_address
     *
     * @mbg.generated Fri May 29 13:52:00 CST 2020
     */
    private String worksAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.works_userid
     *
     * @mbg.generated Fri May 29 13:52:00 CST 2020
     */
    private Long worksUserid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.works_id
     *
     * @return the value of works.works_id
     *
     * @mbg.generated Fri May 29 13:52:00 CST 2020
     */
    public Long getWorksId() {
        return worksId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.works_id
     *
     * @param worksId the value for works.works_id
     *
     * @mbg.generated Fri May 29 13:52:00 CST 2020
     */
    public void setWorksId(Long worksId) {
        this.worksId = worksId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.works_img
     *
     * @return the value of works.works_img
     *
     * @mbg.generated Fri May 29 13:52:00 CST 2020
     */
    public String getWorksImg() {
        return worksImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.works_img
     *
     * @param worksImg the value for works.works_img
     *
     * @mbg.generated Fri May 29 13:52:00 CST 2020
     */
    public void setWorksImg(String worksImg) {
        this.worksImg = worksImg == null ? null : worksImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.works_describe
     *
     * @return the value of works.works_describe
     *
     * @mbg.generated Fri May 29 13:52:00 CST 2020
     */
    public String getWorksDescribe() {
        return worksDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.works_describe
     *
     * @param worksDescribe the value for works.works_describe
     *
     * @mbg.generated Fri May 29 13:52:00 CST 2020
     */
    public void setWorksDescribe(String worksDescribe) {
        this.worksDescribe = worksDescribe == null ? null : worksDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.works_equiment
     *
     * @return the value of works.works_equiment
     *
     * @mbg.generated Fri May 29 13:52:00 CST 2020
     */
    public String getWorksEquiment() {
        return worksEquiment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.works_equiment
     *
     * @param worksEquiment the value for works.works_equiment
     *
     * @mbg.generated Fri May 29 13:52:00 CST 2020
     */
    public void setWorksEquiment(String worksEquiment) {
        this.worksEquiment = worksEquiment == null ? null : worksEquiment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.works_time
     *
     * @return the value of works.works_time
     *
     * @mbg.generated Fri May 29 13:52:00 CST 2020
     */
    public String getWorksTime() {
        return worksTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.works_time
     *
     * @param worksTime the value for works.works_time
     *
     * @mbg.generated Fri May 29 13:52:00 CST 2020
     */
    public void setWorksTime(String worksTime) {
        this.worksTime = worksTime == null ? null : worksTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.works_style
     *
     * @return the value of works.works_style
     *
     * @mbg.generated Fri May 29 13:52:00 CST 2020
     */
    public String getWorksStyle() {
        return worksStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.works_style
     *
     * @param worksStyle the value for works.works_style
     *
     * @mbg.generated Fri May 29 13:52:00 CST 2020
     */
    public void setWorksStyle(String worksStyle) {
        this.worksStyle = worksStyle == null ? null : worksStyle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.works_givephoto
     *
     * @return the value of works.works_givephoto
     *
     * @mbg.generated Fri May 29 13:52:00 CST 2020
     */
    public Integer getWorksGivephoto() {
        return worksGivephoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.works_givephoto
     *
     * @param worksGivephoto the value for works.works_givephoto
     *
     * @mbg.generated Fri May 29 13:52:00 CST 2020
     */
    public void setWorksGivephoto(Integer worksGivephoto) {
        this.worksGivephoto = worksGivephoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.works_address
     *
     * @return the value of works.works_address
     *
     * @mbg.generated Fri May 29 13:52:00 CST 2020
     */
    public String getWorksAddress() {
        return worksAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.works_address
     *
     * @param worksAddress the value for works.works_address
     *
     * @mbg.generated Fri May 29 13:52:00 CST 2020
     */
    public void setWorksAddress(String worksAddress) {
        this.worksAddress = worksAddress == null ? null : worksAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.works_userid
     *
     * @return the value of works.works_userid
     *
     * @mbg.generated Fri May 29 13:52:00 CST 2020
     */
    public Long getWorksUserid() {
        return worksUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.works_userid
     *
     * @param worksUserid the value for works.works_userid
     *
     * @mbg.generated Fri May 29 13:52:00 CST 2020
     */
    public void setWorksUserid(Long worksUserid) {
        this.worksUserid = worksUserid;
    }
}