package com.example.miniprogram.entity;

import java.util.ArrayList;
import java.util.List;

public class WorksExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table works
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table works
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table works
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    public WorksExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table works
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table works
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andWorksIdIsNull() {
            addCriterion("works_id is null");
            return (Criteria) this;
        }

        public Criteria andWorksIdIsNotNull() {
            addCriterion("works_id is not null");
            return (Criteria) this;
        }

        public Criteria andWorksIdEqualTo(Long value) {
            addCriterion("works_id =", value, "worksId");
            return (Criteria) this;
        }

        public Criteria andWorksIdNotEqualTo(Long value) {
            addCriterion("works_id <>", value, "worksId");
            return (Criteria) this;
        }

        public Criteria andWorksIdGreaterThan(Long value) {
            addCriterion("works_id >", value, "worksId");
            return (Criteria) this;
        }

        public Criteria andWorksIdGreaterThanOrEqualTo(Long value) {
            addCriterion("works_id >=", value, "worksId");
            return (Criteria) this;
        }

        public Criteria andWorksIdLessThan(Long value) {
            addCriterion("works_id <", value, "worksId");
            return (Criteria) this;
        }

        public Criteria andWorksIdLessThanOrEqualTo(Long value) {
            addCriterion("works_id <=", value, "worksId");
            return (Criteria) this;
        }

        public Criteria andWorksIdIn(List<Long> values) {
            addCriterion("works_id in", values, "worksId");
            return (Criteria) this;
        }

        public Criteria andWorksIdNotIn(List<Long> values) {
            addCriterion("works_id not in", values, "worksId");
            return (Criteria) this;
        }

        public Criteria andWorksIdBetween(Long value1, Long value2) {
            addCriterion("works_id between", value1, value2, "worksId");
            return (Criteria) this;
        }

        public Criteria andWorksIdNotBetween(Long value1, Long value2) {
            addCriterion("works_id not between", value1, value2, "worksId");
            return (Criteria) this;
        }

        public Criteria andWorksImgIsNull() {
            addCriterion("works_img is null");
            return (Criteria) this;
        }

        public Criteria andWorksImgIsNotNull() {
            addCriterion("works_img is not null");
            return (Criteria) this;
        }

        public Criteria andWorksImgEqualTo(String value) {
            addCriterion("works_img =", value, "worksImg");
            return (Criteria) this;
        }

        public Criteria andWorksImgNotEqualTo(String value) {
            addCriterion("works_img <>", value, "worksImg");
            return (Criteria) this;
        }

        public Criteria andWorksImgGreaterThan(String value) {
            addCriterion("works_img >", value, "worksImg");
            return (Criteria) this;
        }

        public Criteria andWorksImgGreaterThanOrEqualTo(String value) {
            addCriterion("works_img >=", value, "worksImg");
            return (Criteria) this;
        }

        public Criteria andWorksImgLessThan(String value) {
            addCriterion("works_img <", value, "worksImg");
            return (Criteria) this;
        }

        public Criteria andWorksImgLessThanOrEqualTo(String value) {
            addCriterion("works_img <=", value, "worksImg");
            return (Criteria) this;
        }

        public Criteria andWorksImgLike(String value) {
            addCriterion("works_img like", value, "worksImg");
            return (Criteria) this;
        }

        public Criteria andWorksImgNotLike(String value) {
            addCriterion("works_img not like", value, "worksImg");
            return (Criteria) this;
        }

        public Criteria andWorksImgIn(List<String> values) {
            addCriterion("works_img in", values, "worksImg");
            return (Criteria) this;
        }

        public Criteria andWorksImgNotIn(List<String> values) {
            addCriterion("works_img not in", values, "worksImg");
            return (Criteria) this;
        }

        public Criteria andWorksImgBetween(String value1, String value2) {
            addCriterion("works_img between", value1, value2, "worksImg");
            return (Criteria) this;
        }

        public Criteria andWorksImgNotBetween(String value1, String value2) {
            addCriterion("works_img not between", value1, value2, "worksImg");
            return (Criteria) this;
        }

        public Criteria andWorksDescribeIsNull() {
            addCriterion("works_describe is null");
            return (Criteria) this;
        }

        public Criteria andWorksDescribeIsNotNull() {
            addCriterion("works_describe is not null");
            return (Criteria) this;
        }

        public Criteria andWorksDescribeEqualTo(String value) {
            addCriterion("works_describe =", value, "worksDescribe");
            return (Criteria) this;
        }

        public Criteria andWorksDescribeNotEqualTo(String value) {
            addCriterion("works_describe <>", value, "worksDescribe");
            return (Criteria) this;
        }

        public Criteria andWorksDescribeGreaterThan(String value) {
            addCriterion("works_describe >", value, "worksDescribe");
            return (Criteria) this;
        }

        public Criteria andWorksDescribeGreaterThanOrEqualTo(String value) {
            addCriterion("works_describe >=", value, "worksDescribe");
            return (Criteria) this;
        }

        public Criteria andWorksDescribeLessThan(String value) {
            addCriterion("works_describe <", value, "worksDescribe");
            return (Criteria) this;
        }

        public Criteria andWorksDescribeLessThanOrEqualTo(String value) {
            addCriterion("works_describe <=", value, "worksDescribe");
            return (Criteria) this;
        }

        public Criteria andWorksDescribeLike(String value) {
            addCriterion("works_describe like", value, "worksDescribe");
            return (Criteria) this;
        }

        public Criteria andWorksDescribeNotLike(String value) {
            addCriterion("works_describe not like", value, "worksDescribe");
            return (Criteria) this;
        }

        public Criteria andWorksDescribeIn(List<String> values) {
            addCriterion("works_describe in", values, "worksDescribe");
            return (Criteria) this;
        }

        public Criteria andWorksDescribeNotIn(List<String> values) {
            addCriterion("works_describe not in", values, "worksDescribe");
            return (Criteria) this;
        }

        public Criteria andWorksDescribeBetween(String value1, String value2) {
            addCriterion("works_describe between", value1, value2, "worksDescribe");
            return (Criteria) this;
        }

        public Criteria andWorksDescribeNotBetween(String value1, String value2) {
            addCriterion("works_describe not between", value1, value2, "worksDescribe");
            return (Criteria) this;
        }

        public Criteria andWorksEquimentIsNull() {
            addCriterion("works_equiment is null");
            return (Criteria) this;
        }

        public Criteria andWorksEquimentIsNotNull() {
            addCriterion("works_equiment is not null");
            return (Criteria) this;
        }

        public Criteria andWorksEquimentEqualTo(String value) {
            addCriterion("works_equiment =", value, "worksEquiment");
            return (Criteria) this;
        }

        public Criteria andWorksEquimentNotEqualTo(String value) {
            addCriterion("works_equiment <>", value, "worksEquiment");
            return (Criteria) this;
        }

        public Criteria andWorksEquimentGreaterThan(String value) {
            addCriterion("works_equiment >", value, "worksEquiment");
            return (Criteria) this;
        }

        public Criteria andWorksEquimentGreaterThanOrEqualTo(String value) {
            addCriterion("works_equiment >=", value, "worksEquiment");
            return (Criteria) this;
        }

        public Criteria andWorksEquimentLessThan(String value) {
            addCriterion("works_equiment <", value, "worksEquiment");
            return (Criteria) this;
        }

        public Criteria andWorksEquimentLessThanOrEqualTo(String value) {
            addCriterion("works_equiment <=", value, "worksEquiment");
            return (Criteria) this;
        }

        public Criteria andWorksEquimentLike(String value) {
            addCriterion("works_equiment like", value, "worksEquiment");
            return (Criteria) this;
        }

        public Criteria andWorksEquimentNotLike(String value) {
            addCriterion("works_equiment not like", value, "worksEquiment");
            return (Criteria) this;
        }

        public Criteria andWorksEquimentIn(List<String> values) {
            addCriterion("works_equiment in", values, "worksEquiment");
            return (Criteria) this;
        }

        public Criteria andWorksEquimentNotIn(List<String> values) {
            addCriterion("works_equiment not in", values, "worksEquiment");
            return (Criteria) this;
        }

        public Criteria andWorksEquimentBetween(String value1, String value2) {
            addCriterion("works_equiment between", value1, value2, "worksEquiment");
            return (Criteria) this;
        }

        public Criteria andWorksEquimentNotBetween(String value1, String value2) {
            addCriterion("works_equiment not between", value1, value2, "worksEquiment");
            return (Criteria) this;
        }

        public Criteria andWorksTimeIsNull() {
            addCriterion("works_time is null");
            return (Criteria) this;
        }

        public Criteria andWorksTimeIsNotNull() {
            addCriterion("works_time is not null");
            return (Criteria) this;
        }

        public Criteria andWorksTimeEqualTo(String value) {
            addCriterion("works_time =", value, "worksTime");
            return (Criteria) this;
        }

        public Criteria andWorksTimeNotEqualTo(String value) {
            addCriterion("works_time <>", value, "worksTime");
            return (Criteria) this;
        }

        public Criteria andWorksTimeGreaterThan(String value) {
            addCriterion("works_time >", value, "worksTime");
            return (Criteria) this;
        }

        public Criteria andWorksTimeGreaterThanOrEqualTo(String value) {
            addCriterion("works_time >=", value, "worksTime");
            return (Criteria) this;
        }

        public Criteria andWorksTimeLessThan(String value) {
            addCriterion("works_time <", value, "worksTime");
            return (Criteria) this;
        }

        public Criteria andWorksTimeLessThanOrEqualTo(String value) {
            addCriterion("works_time <=", value, "worksTime");
            return (Criteria) this;
        }

        public Criteria andWorksTimeLike(String value) {
            addCriterion("works_time like", value, "worksTime");
            return (Criteria) this;
        }

        public Criteria andWorksTimeNotLike(String value) {
            addCriterion("works_time not like", value, "worksTime");
            return (Criteria) this;
        }

        public Criteria andWorksTimeIn(List<String> values) {
            addCriterion("works_time in", values, "worksTime");
            return (Criteria) this;
        }

        public Criteria andWorksTimeNotIn(List<String> values) {
            addCriterion("works_time not in", values, "worksTime");
            return (Criteria) this;
        }

        public Criteria andWorksTimeBetween(String value1, String value2) {
            addCriterion("works_time between", value1, value2, "worksTime");
            return (Criteria) this;
        }

        public Criteria andWorksTimeNotBetween(String value1, String value2) {
            addCriterion("works_time not between", value1, value2, "worksTime");
            return (Criteria) this;
        }

        public Criteria andWorksStyleIsNull() {
            addCriterion("works_style is null");
            return (Criteria) this;
        }

        public Criteria andWorksStyleIsNotNull() {
            addCriterion("works_style is not null");
            return (Criteria) this;
        }

        public Criteria andWorksStyleEqualTo(String value) {
            addCriterion("works_style =", value, "worksStyle");
            return (Criteria) this;
        }

        public Criteria andWorksStyleNotEqualTo(String value) {
            addCriterion("works_style <>", value, "worksStyle");
            return (Criteria) this;
        }

        public Criteria andWorksStyleGreaterThan(String value) {
            addCriterion("works_style >", value, "worksStyle");
            return (Criteria) this;
        }

        public Criteria andWorksStyleGreaterThanOrEqualTo(String value) {
            addCriterion("works_style >=", value, "worksStyle");
            return (Criteria) this;
        }

        public Criteria andWorksStyleLessThan(String value) {
            addCriterion("works_style <", value, "worksStyle");
            return (Criteria) this;
        }

        public Criteria andWorksStyleLessThanOrEqualTo(String value) {
            addCriterion("works_style <=", value, "worksStyle");
            return (Criteria) this;
        }

        public Criteria andWorksStyleLike(String value) {
            addCriterion("works_style like", value, "worksStyle");
            return (Criteria) this;
        }

        public Criteria andWorksStyleNotLike(String value) {
            addCriterion("works_style not like", value, "worksStyle");
            return (Criteria) this;
        }

        public Criteria andWorksStyleIn(List<String> values) {
            addCriterion("works_style in", values, "worksStyle");
            return (Criteria) this;
        }

        public Criteria andWorksStyleNotIn(List<String> values) {
            addCriterion("works_style not in", values, "worksStyle");
            return (Criteria) this;
        }

        public Criteria andWorksStyleBetween(String value1, String value2) {
            addCriterion("works_style between", value1, value2, "worksStyle");
            return (Criteria) this;
        }

        public Criteria andWorksStyleNotBetween(String value1, String value2) {
            addCriterion("works_style not between", value1, value2, "worksStyle");
            return (Criteria) this;
        }

        public Criteria andWorksGivephotoIsNull() {
            addCriterion("works_givephoto is null");
            return (Criteria) this;
        }

        public Criteria andWorksGivephotoIsNotNull() {
            addCriterion("works_givephoto is not null");
            return (Criteria) this;
        }

        public Criteria andWorksGivephotoEqualTo(Integer value) {
            addCriterion("works_givephoto =", value, "worksGivephoto");
            return (Criteria) this;
        }

        public Criteria andWorksGivephotoNotEqualTo(Integer value) {
            addCriterion("works_givephoto <>", value, "worksGivephoto");
            return (Criteria) this;
        }

        public Criteria andWorksGivephotoGreaterThan(Integer value) {
            addCriterion("works_givephoto >", value, "worksGivephoto");
            return (Criteria) this;
        }

        public Criteria andWorksGivephotoGreaterThanOrEqualTo(Integer value) {
            addCriterion("works_givephoto >=", value, "worksGivephoto");
            return (Criteria) this;
        }

        public Criteria andWorksGivephotoLessThan(Integer value) {
            addCriterion("works_givephoto <", value, "worksGivephoto");
            return (Criteria) this;
        }

        public Criteria andWorksGivephotoLessThanOrEqualTo(Integer value) {
            addCriterion("works_givephoto <=", value, "worksGivephoto");
            return (Criteria) this;
        }

        public Criteria andWorksGivephotoIn(List<Integer> values) {
            addCriterion("works_givephoto in", values, "worksGivephoto");
            return (Criteria) this;
        }

        public Criteria andWorksGivephotoNotIn(List<Integer> values) {
            addCriterion("works_givephoto not in", values, "worksGivephoto");
            return (Criteria) this;
        }

        public Criteria andWorksGivephotoBetween(Integer value1, Integer value2) {
            addCriterion("works_givephoto between", value1, value2, "worksGivephoto");
            return (Criteria) this;
        }

        public Criteria andWorksGivephotoNotBetween(Integer value1, Integer value2) {
            addCriterion("works_givephoto not between", value1, value2, "worksGivephoto");
            return (Criteria) this;
        }

        public Criteria andWorksAddressIsNull() {
            addCriterion("works_address is null");
            return (Criteria) this;
        }

        public Criteria andWorksAddressIsNotNull() {
            addCriterion("works_address is not null");
            return (Criteria) this;
        }

        public Criteria andWorksAddressEqualTo(String value) {
            addCriterion("works_address =", value, "worksAddress");
            return (Criteria) this;
        }

        public Criteria andWorksAddressNotEqualTo(String value) {
            addCriterion("works_address <>", value, "worksAddress");
            return (Criteria) this;
        }

        public Criteria andWorksAddressGreaterThan(String value) {
            addCriterion("works_address >", value, "worksAddress");
            return (Criteria) this;
        }

        public Criteria andWorksAddressGreaterThanOrEqualTo(String value) {
            addCriterion("works_address >=", value, "worksAddress");
            return (Criteria) this;
        }

        public Criteria andWorksAddressLessThan(String value) {
            addCriterion("works_address <", value, "worksAddress");
            return (Criteria) this;
        }

        public Criteria andWorksAddressLessThanOrEqualTo(String value) {
            addCriterion("works_address <=", value, "worksAddress");
            return (Criteria) this;
        }

        public Criteria andWorksAddressLike(String value) {
            addCriterion("works_address like", value, "worksAddress");
            return (Criteria) this;
        }

        public Criteria andWorksAddressNotLike(String value) {
            addCriterion("works_address not like", value, "worksAddress");
            return (Criteria) this;
        }

        public Criteria andWorksAddressIn(List<String> values) {
            addCriterion("works_address in", values, "worksAddress");
            return (Criteria) this;
        }

        public Criteria andWorksAddressNotIn(List<String> values) {
            addCriterion("works_address not in", values, "worksAddress");
            return (Criteria) this;
        }

        public Criteria andWorksAddressBetween(String value1, String value2) {
            addCriterion("works_address between", value1, value2, "worksAddress");
            return (Criteria) this;
        }

        public Criteria andWorksAddressNotBetween(String value1, String value2) {
            addCriterion("works_address not between", value1, value2, "worksAddress");
            return (Criteria) this;
        }

        public Criteria andWorksUseridIsNull() {
            addCriterion("works_userid is null");
            return (Criteria) this;
        }

        public Criteria andWorksUseridIsNotNull() {
            addCriterion("works_userid is not null");
            return (Criteria) this;
        }

        public Criteria andWorksUseridEqualTo(Long value) {
            addCriterion("works_userid =", value, "worksUserid");
            return (Criteria) this;
        }

        public Criteria andWorksUseridNotEqualTo(Long value) {
            addCriterion("works_userid <>", value, "worksUserid");
            return (Criteria) this;
        }

        public Criteria andWorksUseridGreaterThan(Long value) {
            addCriterion("works_userid >", value, "worksUserid");
            return (Criteria) this;
        }

        public Criteria andWorksUseridGreaterThanOrEqualTo(Long value) {
            addCriterion("works_userid >=", value, "worksUserid");
            return (Criteria) this;
        }

        public Criteria andWorksUseridLessThan(Long value) {
            addCriterion("works_userid <", value, "worksUserid");
            return (Criteria) this;
        }

        public Criteria andWorksUseridLessThanOrEqualTo(Long value) {
            addCriterion("works_userid <=", value, "worksUserid");
            return (Criteria) this;
        }

        public Criteria andWorksUseridIn(List<Long> values) {
            addCriterion("works_userid in", values, "worksUserid");
            return (Criteria) this;
        }

        public Criteria andWorksUseridNotIn(List<Long> values) {
            addCriterion("works_userid not in", values, "worksUserid");
            return (Criteria) this;
        }

        public Criteria andWorksUseridBetween(Long value1, Long value2) {
            addCriterion("works_userid between", value1, value2, "worksUserid");
            return (Criteria) this;
        }

        public Criteria andWorksUseridNotBetween(Long value1, Long value2) {
            addCriterion("works_userid not between", value1, value2, "worksUserid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table works
     *
     * @mbg.generated do_not_delete_during_merge Sun May 24 19:51:25 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table works
     *
     * @mbg.generated Sun May 24 19:51:25 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}